### ISSUE TITLE
Error when installing linters by yeoman generator.

### ISSUE THREAD

**Issue by neerajsachan** [rcorp/standard-project-structure#63]
When we install linters by yeoman generator it gives following type errors :                                             `Error: Cannot find module '/var/www/html/plugs/grunt/aliases.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at writing (/var/www/html/plugs/node_modules/standard-project-structure/generators/linter/index.js:51:21)
    at Object.<anonymous> (/var/www/html/plugs/node_modules/yeoman-generator/lib/base.js:439:23)
    at /var/www/html/plugs/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /var/www/html/plugs/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /var/www/html/plugs/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:566:20)`

**Comment by gaurav21r** [comment]
Solved in https://github.com/rcorp/standard-project-structure/commit/7752d8f58de830eddff56578b5d3181068d35922
